    INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('João do Nome-Bem-Grande da Silva', 1500.55, 10.0, 1);
    INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Maria Joaquina', 1800.50, 20.5, 2);
    INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Darcy', 2000.00, 25.55, 3);